field: 4aa3edd5-8bfc-42ba-b540-5de6dd750eb5 # Riders
fieldLayouts:
  58640ac2-58c7-4775-8d4b-233e8f2c7cc1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9361d4cf-aab0-46e9-b6b7-c2bc91059832 # Photo
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2db0199-1d34-455c-acf0-5534c967be53
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f6647277-94f6-4b5c-a69c-869e61bc7cb0 # Full Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 053e1946-68bf-4fb4-84ac-bc48cd28b3a5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 843a6afc-942f-4fcd-9d44-5980e23622ee # Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c0dd5fe-42e8-4273-b9c2-3cf840861959
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4d1ea4b2-915e-4daa-bb75-7631e06228d5
        userCondition: null
fields:
  843a6afc-942f-4fcd-9d44-5980e23622ee: # Description
    columnSuffix: xiccetpv
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 2
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9361d4cf-aab0-46e9-b6b7-c2bc91059832: # Photo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: photo
    instructions: null
    name: Photo
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:e2e255b6-f8af-4884-acb4-9a0c9ecd803d' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:e2e255b6-f8af-4884-acb4-9a0c9ecd803d' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add a photo'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:e2e255b6-f8af-4884-acb4-9a0c9ecd803d' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f6647277-94f6-4b5c-a69c-869e61bc7cb0: # Full Name
    columnSuffix: zdjhfozj
    contentColumnType: text
    fieldGroup: null
    handle: fullName
    instructions: null
    name: 'Full Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: rider
name: Rider
sortOrder: 1
