fieldLayouts:
  dd17f29f-8a4b-4188-adef-882ea742dc3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a25d5806-91e4-4856-9334-d2e03ee8d82e # Nav Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a21fa4f-4926-438e-89ef-b98b31705ef1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1089e6f8-414a-4f63-b27f-a5bab1707a72
        userCondition: null
handle: header
name: Header
sortOrder: 1
