defaultPlacement: end
enableVersioning: true
handle: storiesListing
name: 'Stories Listing'
propagationMethod: all
siteSettings:
  148b99ca-50e0-4be3-9f95-942fcd12ecd5: # craftcms-tester
    enabledByDefault: true
    hasUrls: true
    template: stories\index.twig
    uriFormat: stories
type: single
